### ISSUE TITLE
Cuprous oxide ingot not defined

### ISSUE THREAD

**Issue by EmeraldMT** [forked-from-1kasper/loria#1]
2020-07-17 04:07:37: ERROR[Server]: Item "loria:cuprous_oxide_ingot" not defined

Trying to place the unknown item I got while using the refiner let me find out what it was so that was useful.

What probably happened is I refined a cuprous oxide as I didn't turn the refiner off before putting in 2 cuprous oxide and a balloon to get oxygen gas.

**Comment by rzrn** [comment]
Thanks, it should work correctly in the latest build (20w29m).
