### ISSUE TITLE
Craft guide change needed

### ISSUE THREAD

**Issue by EmeraldMT** [forked-from-1kasper/loria#2]
I had a lot of struggle figuring out how to get a furnace. Eventually I figured out the item listed as 'gas' in the craft guide is in fact the gas powered furnace.

In the line:
15 | Lead × 3 | Gas × 1
'Gas' should be changed to 'Gas powered furnace' (or whatever name it is given in the game) to indicate that it is the furnace the player needs to craft.

(As an aside, you may be interested in my attempt to write a beginner guide for the game after a lot of time prodding at the craft guide. I'm not sure if I found the most optimal way for the player to obtain oxygen. https://docs.google.com/document/d/1uhYAhYlVLJ--hFerAm26MYybIukFlbA8UeSHyIyzsXQ/edit?usp=sharing )

**Comment by rzrn** [comment]
>'Gas' should be changed to 'Gas powered furnace'

OK, renamed.

>or whatever name it is given in the game

In-game name (≠ description that is shown to the player) is `furnace:gas`. Craft list is generated by script that throws out the first part of name (specifying the mod). Now this case (`furnace:gas`) is handled in a special way.

>As an aside, you may be interested in my attempt to write a beginner guide for the game after a lot of time prodding at the craft guide. 

If you wish, I can add a link to this guide on [ContentDB](https://content.minetest.net/packages/siegment/loria/) (or add the link to it later).

>I'm not sure if I found the most optimal way for the player to obtain oxygen. 

Most optimal way is probably to using mercury oxide (red/orange node in the desert) or sodium peroxide (yellow node in yellow biome).

>Todo: test if other gases will power machines.

Currently no.

**Comment by EmeraldMT** [comment]
If you make a forum topic for this game then when the guide is finished, I can add it to the forum topic. I'll have to try the mercury oxide and sodium peroxide methods and edit the guide accordingly. I hope you're planning a guide to the electricity mod stuff soon. :)

**Comment by rzrn** [comment]
>If you make a forum topic for this game

https://forum.minetest.net/viewtopic.php?f=50&t=25095
