### ISSUE TITLE
Stacked buckets behave weirdly

### ISSUE THREAD

**Issue by FavoritoHJS** [forked-from-1kasper/loria#6]
The stack of 2 buckets you recieve when crafting Hydrogen Balloons sometimes turns into a stack of 1 bucket without giving the other bucket back.

Probably an engine bug, but can be worked around by, instead of giving a stack of 2 buckets, giving 2 stacks of 1 bucket each.

PS: Can you add an extra balloon and bucket to the starting items? You have exactly the ammount of buckets you need to get more buckets, making fluid management a nightmare, and godforbid you want to use silane as a fuel when you also need recipes which require both buckets.

PPS: Some slight digging/walking sounds would be appreciated. Not much, but enough to break the silence a tad.

**Comment by rzrn** [comment]
>Probably an engine bug, but can be worked around by, instead of giving a stack of 2 buckets, giving 2 stacks of 1 bucket each.

Pushed [fix](https://github.com/forked-from-1kasper/loria/commit/44e4f6076311c6bb1874d7a6396022b1d9a99479), try it out.

>PS: Can you add an extra balloon and bucket to the starting items?

[Added](https://github.com/forked-from-1kasper/loria/commit/e4a70156741f21dec9b7dc3c1c6497d3f5778f67) ability to configure (Settings → All Settings → Games → Loria) startup inventory, so you may add as many buckets as you want.

>PPS: Some slight digging/walking sounds would be appreciated. Not much, but enough to break the silence a tad.

Unfortunately, I am very bad at sound design.

**Comment by FavoritoHJS** [comment]
Yup, it seems like stacked buckets are now given individually, working around this bug. Closing.
